eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
keycloak:
  auth-server-url: https://login.archi-lab.io/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  public-client: false
  realm: archilab
  resource: proposal-service
server:
  port: 9002
  use-forward-headers: true
spring:
  application:
    name: proposal-service
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    data-username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    - root: WARN
    - org.springframework.web: WARN
    - org.hibernate: WARN
